### ISSUE TITLE
Issue with installing SPLASH

### ISSUE THREAD

**Issue by cecile-meier-scherling** [refresh-bio/SPLASH#5]
Hello, I am trying to install SPLASH but am running into an error. 

When I run the precompiled binaries:
```
curl -L https://github.com/refresh-bio/SPLASH/releases/download/v2.1.4/splash-2.1.4.linux.x64.tar.gz | tar xz
cd example
./run-example.sh
```

But I am running into the following issue, which seems to be in the subprocess.py:
```
Traceback (most recent call last):
  File "/Users/cmeiersc/Dropbox (Brown)/Brown/git/splash/example/../splash", line 264, in <module>
    p = subprocess.Popen(executable_path, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/Users/cmeiersc/opt/anaconda3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/cmeiersc/opt/anaconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '../satc'
```

In addition, when compiling SPLASH from the source with the following code:
```
git clone https://github.com/refresh-bio/splash
cd splash
make -j
sudo make install
```

However, I am getting the following issue and as a result splash is not completely installed:
```
g++-11 -fPIC -Wall -O3 -m64 -std=c++17 -pthread -I libs -I libs/mimalloc/include -fpermissive -c src/satc/satc.cpp -o src/satc/satc.o
make: g++-11: No such file or directory
g++-11 -fPIC -Wall -O3 -m64 -std=c++17 -pthread -I libs -I libs/mimalloc/include -fpermissive -c src/common/kmc_api/kmc_file.cpp -o src/common/kmc_api/kmc_file.o
make: g++-11: No such file or directory
g++-11 -fPIC -Wall -O3 -m64 -std=c++17 -pthread -I libs -I libs/mimalloc/include -fpermissive -c src/common/kmc_api/mmer.cpp -o src/common/kmc_api/mmer.o
make: g++-11: No such file or directory
g++-11 -fPIC -Wall -O3 -m64 -std=c++17 -pthread -I libs -I libs/mimalloc/include -fpermissive -c src/common/kmc_api/kmer_api.cpp -o src/common/kmc_api/kmer_api.o
make: g++-11: No such file or directory
make: *** [src/satc/satc.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [src/common/kmc_api/kmc_file.o] Error 1
make: *** [src/common/kmc_api/kmer_api.o] Error 1
make: *** [src/common/kmc_api/mmer.o] Error 1
g++-11 -fPIC -Wall -O3 -m64 -std=c++17 -pthread -I libs -I libs/mimalloc/include -fpermissive -c src/satc/satc.cpp -o src/satc/satc.o
make: g++-11: No such file or directory
make: *** [src/satc/satc.o] Error 1
```

Are there any installations I am missing? 

Currently I am running the code as described above. I have also tried to run each individually and then run the example as described on the GitHub, but splash seems not to be installed. 

I would greatly appreciate any suggestions!

**Comment by marekkokot** [comment]
Hello
thanks! What operating system are you using?
Basing on the errors I assume this is MAC OS.
Unfortunately, the current version only works on Linux (we have a not-yet-published version for MAC OS).
Are you able to try SPLASH on Linux?

**Comment by cecile-meier-scherling** [comment]
Hello @marekkokot,
thank you for your response! Yes, I was able to install splash on Linux.
